<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4yzsgpy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4yzsgpy/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4yzsgpy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4yzsgpy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4yzsgpy\appProdProjectContainer(array(
    'container.build_hash' => '4yzsgpy',
    'container.build_id' => 'de83071d',
    'container.build_time' => 1526973971,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4yzsgpy');
