<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTjjvbn9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTjjvbn9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTjjvbn9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTjjvbn9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTjjvbn9\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Tjjvbn9',
    'container.build_id' => '1a1e71a3',
    'container.build_time' => 1526992105,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTjjvbn9');
