<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKmql1i8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKmql1i8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKmql1i8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKmql1i8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKmql1i8\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kmql1i8',
    'container.build_id' => 'bdea0d77',
    'container.build_time' => 1526976972,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKmql1i8');
