<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTyl5xxb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTyl5xxb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTyl5xxb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTyl5xxb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTyl5xxb\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Tyl5xxb',
    'container.build_id' => '81cf1898',
    'container.build_time' => 1526301273,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTyl5xxb');
